workspace "Architecture — awesome-compose" "Auto-generated by nfr-review v<version> {
    !identifiers hierarchical

    model {
        awesome_compose = softwareSystem "awesome-compose" "Primary system under analysis" {
            ml_awesome_compose_fastapi_1641d4 = component "fastapi" "ML training pipeline" "Python"
            nested_awesome_compose_react_nginx_73b3a4 = component "react-nginx" "Nested project component" "Node.js, React"
        }
        infra_mysql_430005 = softwareSystem "Mysql" "Infrastructure: Mysql" {
            tags "External"
        }
        infra_db_7bdc25 = softwareSystem "Db" "Infrastructure: Db" {
            tags "External"
        }
        infra_www_duckdns_org_82df5b = softwareSystem "Www Duckdns Org" "Infrastructure: Www Duckdns Org" {
            tags "External"
        }
        infra_www_noip_com_1b1fca = softwareSystem "Www Noip Com" "Infrastructure: Www Noip Com" {
            tags "External"
        }
        ml_awesome_compose_fastapi_1641d4 -> infra_db_7bdc25 "JDBC connection to postgresql at 'db'" "jdbc:postgresql"
        ml_awesome_compose_fastapi_1641d4 -> infra_mysql_430005 "JDBC connection to mysql at 'mysql'" "jdbc:mysql"
        ml_awesome_compose_fastapi_1641d4 -> infra_www_duckdns_org_82df5b "HTTP endpoint at 'www.duckdns.org'" "http"
        ml_awesome_compose_fastapi_1641d4 -> infra_www_noip_com_1b1fca "HTTP endpoint at 'www.noip.com'" "http"
    }

    views {
        systemLandscape "landscape" {
            include *
            autoLayout tb
        }
        container awesome_compose "containers" {
            include *
            autoLayout lr
        }
        styles {
            element "External" {
                shape RoundedBox
                background #999999
                color #ffffff
            }
            element "Element" {
                shape RoundedBox
            }
            relationship "CrossRepo" {
                color #ff0000
                style dashed
            }
        }
    }
}
