workspace "Architecture — buf-tour" "Auto-generated by nfr-review v<version> {
    !identifiers hierarchical

    model {
    }

    views {
        systemLandscape "landscape" {
            include *
            autoLayout tb
        }
        styles {
            element "External" {
                shape RoundedBox
                background #999999
                color #ffffff
            }
            element "Element" {
                shape RoundedBox
            }
            relationship "CrossRepo" {
                color #ff0000
                style dashed
            }
        }
    }
}
