workspace "Architecture — gin" "Auto-generated by nfr-review v<version> {
    !identifiers hierarchical

    model {
        gin = softwareSystem "gin" "Primary system under analysis" {
            comp_gin_985adc = component "gin" "Root project component" "Go"
            infra_mongodb_1cc9a7 = component "Mongodb" "Infrastructure: Mongodb"
        }
        infra_pkg_go_dev_e4c157 = softwareSystem "Pkg Go Dev" "Infrastructure: Pkg Go Dev" {
            tags "External"
        }
        infra_gin_gonic_com_3b1b0e = softwareSystem "Gin Gonic Com" "Infrastructure: Gin Gonic Com" {
            tags "External"
        }
        infra_github_com_3aeb00 = softwareSystem "Github Com" "Infrastructure: Github Com" {
            tags "External"
        }
        comp_gin_985adc -> infra_gin_gonic_com_3b1b0e "HTTP endpoint at 'gin-gonic.com'" "http"
        comp_gin_985adc -> infra_github_com_3aeb00 "HTTP endpoint at 'github.com'" "http"
        comp_gin_985adc -> infra_mongodb_1cc9a7 "Go module 'go.mongodb.org/mongo-driver' implies gin connects to mongodb" "mongodb"
        comp_gin_985adc -> infra_pkg_go_dev_e4c157 "HTTP endpoint at 'pkg.go.dev'" "http"
    }

    views {
        systemLandscape "landscape" {
            include *
            autoLayout tb
        }
        container gin "containers" {
            include *
            autoLayout lr
        }
        styles {
            element "External" {
                shape RoundedBox
                background #999999
                color #ffffff
            }
            element "Element" {
                shape RoundedBox
            }
            relationship "CrossRepo" {
                color #ff0000
                style dashed
            }
        }
    }
}
