workspace "Architecture — httpx" "Auto-generated by nfr-review v<version> {
    !identifiers hierarchical

    model {
        httpx = softwareSystem "httpx" "Primary system under analysis" {
            comp_httpx_44c3f6 = component "httpx" "Root project component" "Python"
        }
        infra_github_com_3aeb00 = softwareSystem "Github Com" "Infrastructure: Github Com" {
            tags "External"
        }
        infra_gitter_im_a4d514 = softwareSystem "Gitter Im" "Infrastructure: Gitter Im" {
            tags "External"
        }
        infra_http_service_00f8ae = softwareSystem "Http Service" "Infrastructure: Http Service" {
            tags "External"
        }
        comp_httpx_44c3f6 -> infra_github_com_3aeb00 "HTTP endpoint at 'github.com'" "http"
        comp_httpx_44c3f6 -> infra_gitter_im_a4d514 "HTTP endpoint at 'gitter.im'" "http"
        comp_httpx_44c3f6 -> infra_http_service_00f8ae "Python dependency 'httpx' implies httpx connects to http-service" "http"
    }

    views {
        systemLandscape "landscape" {
            include *
            autoLayout tb
        }
        container httpx "containers" {
            include *
            autoLayout lr
        }
        styles {
            element "External" {
                shape RoundedBox
                background #999999
                color #ffffff
            }
            element "Element" {
                shape RoundedBox
            }
            relationship "CrossRepo" {
                color #ff0000
                style dashed
            }
        }
    }
}
