workspace "Architecture — jackson-databind" "Auto-generated by nfr-review v<version> {
    !identifiers hierarchical

    model {
        jackson_databind = softwareSystem "jackson-databind" "Primary system under analysis" {
            comp_jackson_databind_02b469 = component "jackson-databind" "Root project component" "Java"
        }
    }

    views {
        systemLandscape "landscape" {
            include *
            autoLayout tb
        }
        container jackson_databind "containers" {
            include *
            autoLayout lr
        }
        styles {
            element "External" {
                shape RoundedBox
                background #999999
                color #ffffff
            }
            element "Element" {
                shape RoundedBox
            }
            relationship "CrossRepo" {
                color #ff0000
                style dashed
            }
        }
    }
}
