workspace "Architecture — microservices-demo" "Auto-generated by nfr-review v<version> {
    !identifiers hierarchical

    model {
        microservices_demo = softwareSystem "microservices-demo" "Primary system under analysis" {
            k8s_microservices_demo_adservice_0e3a38 = component "adservice" "Kubernetes Deployment workload" "adservice"
            k8s_microservices_demo_cartservice_07d8cc = component "cartservice" "Kubernetes Deployment workload" "cartservice"
            k8s_microservices_demo_checkoutservice_1f4fb5 = component "checkoutservice" "Kubernetes Deployment workload" "checkoutservice"
            k8s_microservices_demo_currencyservice_fd9e0c = component "currencyservice" "Kubernetes Deployment workload" "currencyservice"
            k8s_microservices_demo_emailservice_ee57a0 = component "emailservice" "Kubernetes Deployment workload" "emailservice"
            k8s_microservices_demo_frontend_d31c8b = component "frontend" "Kubernetes Deployment workload" "frontend"
            k8s_microservices_demo_loadgenerator_ad34ea = component "loadgenerator" "Kubernetes Deployment workload" "loadgenerator"
            k8s_microservices_demo_opentelemetrycollector_f2cf2a = component "opentelemetrycollector" "Kubernetes Deployment workload" "opentelemetry-collector-contrib"
            k8s_microservices_demo_paymentservice_42e488 = component "paymentservice" "Kubernetes Deployment workload" "paymentservice"
            k8s_microservices_demo_productcatalogservice_bd42bb = component "productcatalogservice" "Kubernetes Deployment workload" "productcatalogservice"
            k8s_microservices_demo_recommendationservice_3360be = component "recommendationservice" "Kubernetes Deployment workload" "recommendationservice"
            k8s_microservices_demo_redis_cart_fa1f49 = component "redis-cart" "Kubernetes Deployment workload" "redis"
            k8s_microservices_demo_shippingservice_06bbc6 = component "shippingservice" "Kubernetes Deployment workload" "shippingservice"
            k8s_microservices_demo_shoppingassistantservice_cc4140 = component "shoppingassistantservice" "Kubernetes Deployment workload" "shoppingassistantservice"
        }
        k8s_microservices_demo_cartservice_07d8cc -> k8s_microservices_demo_redis_cart_fa1f49 "K8s Deployment 'cartservice' references 'redis-cart' via env REDIS_ADDR" "redis"
        k8s_microservices_demo_checkoutservice_1f4fb5 -> k8s_microservices_demo_cartservice_07d8cc "K8s Deployment 'checkoutservice' references 'cartservice' via env CART_SERVICE_ADDR" "grpc"
        k8s_microservices_demo_checkoutservice_1f4fb5 -> k8s_microservices_demo_cartservice_07d8cc "gRPC call from 'checkoutservice' to 'CartService'" "grpc"
        k8s_microservices_demo_checkoutservice_1f4fb5 -> k8s_microservices_demo_currencyservice_fd9e0c "K8s Deployment 'checkoutservice' references 'currencyservice' via env CURRENCY_SERVICE_ADDR" "grpc"
        k8s_microservices_demo_checkoutservice_1f4fb5 -> k8s_microservices_demo_currencyservice_fd9e0c "gRPC call from 'checkoutservice' to 'CurrencyService'" "grpc"
        k8s_microservices_demo_checkoutservice_1f4fb5 -> k8s_microservices_demo_emailservice_ee57a0 "K8s Deployment 'checkoutservice' references 'emailservice' via env EMAIL_SERVICE_ADDR" "grpc"
        k8s_microservices_demo_checkoutservice_1f4fb5 -> k8s_microservices_demo_emailservice_ee57a0 "gRPC call from 'checkoutservice' to 'EmailService'" "grpc"
        k8s_microservices_demo_checkoutservice_1f4fb5 -> k8s_microservices_demo_paymentservice_42e488 "K8s Deployment 'checkoutservice' references 'paymentservice' via env PAYMENT_SERVICE_ADDR" "grpc"
        k8s_microservices_demo_checkoutservice_1f4fb5 -> k8s_microservices_demo_paymentservice_42e488 "gRPC call from 'checkoutservice' to 'PaymentService'" "grpc"
        k8s_microservices_demo_checkoutservice_1f4fb5 -> k8s_microservices_demo_productcatalogservice_bd42bb "K8s Deployment 'checkoutservice' references 'productcatalogservice' via env PRODUCT_CATALOG_SERVICE_ADDR" "grpc"
        k8s_microservices_demo_checkoutservice_1f4fb5 -> k8s_microservices_demo_productcatalogservice_bd42bb "gRPC call from 'checkoutservice' to 'ProductCatalogService'" "grpc"
        k8s_microservices_demo_checkoutservice_1f4fb5 -> k8s_microservices_demo_shippingservice_06bbc6 "K8s Deployment 'checkoutservice' references 'shippingservice' via env SHIPPING_SERVICE_ADDR" "grpc"
        k8s_microservices_demo_checkoutservice_1f4fb5 -> k8s_microservices_demo_shippingservice_06bbc6 "gRPC call from 'checkoutservice' to 'ShippingService'" "grpc"
        k8s_microservices_demo_frontend_d31c8b -> k8s_microservices_demo_adservice_0e3a38 "K8s Deployment 'frontend' references 'adservice' via env AD_SERVICE_ADDR" "grpc"
        k8s_microservices_demo_frontend_d31c8b -> k8s_microservices_demo_adservice_0e3a38 "gRPC call from 'frontend' to 'AdService'" "grpc"
        k8s_microservices_demo_frontend_d31c8b -> k8s_microservices_demo_cartservice_07d8cc "K8s Deployment 'frontend' references 'cartservice' via env CART_SERVICE_ADDR" "grpc"
        k8s_microservices_demo_frontend_d31c8b -> k8s_microservices_demo_cartservice_07d8cc "gRPC call from 'frontend' to 'CartService'" "grpc"
        k8s_microservices_demo_frontend_d31c8b -> k8s_microservices_demo_checkoutservice_1f4fb5 "K8s Deployment 'frontend' references 'checkoutservice' via env CHECKOUT_SERVICE_ADDR" "grpc"
        k8s_microservices_demo_frontend_d31c8b -> k8s_microservices_demo_checkoutservice_1f4fb5 "gRPC call from 'frontend' to 'CheckoutService'" "grpc"
        k8s_microservices_demo_frontend_d31c8b -> k8s_microservices_demo_currencyservice_fd9e0c "K8s Deployment 'frontend' references 'currencyservice' via env CURRENCY_SERVICE_ADDR" "grpc"
        k8s_microservices_demo_frontend_d31c8b -> k8s_microservices_demo_currencyservice_fd9e0c "gRPC call from 'frontend' to 'CurrencyService'" "grpc"
        k8s_microservices_demo_frontend_d31c8b -> k8s_microservices_demo_productcatalogservice_bd42bb "K8s Deployment 'frontend' references 'productcatalogservice' via env PRODUCT_CATALOG_SERVICE_ADDR" "grpc"
        k8s_microservices_demo_frontend_d31c8b -> k8s_microservices_demo_productcatalogservice_bd42bb "gRPC call from 'frontend' to 'ProductCatalogService'" "grpc"
        k8s_microservices_demo_frontend_d31c8b -> k8s_microservices_demo_recommendationservice_3360be "K8s Deployment 'frontend' references 'recommendationservice' via env RECOMMENDATION_SERVICE_ADDR" "grpc"
        k8s_microservices_demo_frontend_d31c8b -> k8s_microservices_demo_recommendationservice_3360be "gRPC call from 'frontend' to 'RecommendationService'" "grpc"
        k8s_microservices_demo_frontend_d31c8b -> k8s_microservices_demo_shippingservice_06bbc6 "K8s Deployment 'frontend' references 'shippingservice' via env SHIPPING_SERVICE_ADDR" "grpc"
        k8s_microservices_demo_frontend_d31c8b -> k8s_microservices_demo_shippingservice_06bbc6 "gRPC call from 'frontend' to 'ShippingService'" "grpc"
        k8s_microservices_demo_frontend_d31c8b -> k8s_microservices_demo_shoppingassistantservice_cc4140 "K8s Deployment 'frontend' references 'shoppingassistantservice' via env SHOPPING_ASSISTANT_SERVICE_ADDR" "grpc"
        k8s_microservices_demo_loadgenerator_ad34ea -> k8s_microservices_demo_frontend_d31c8b "K8s Deployment 'loadgenerator' references 'frontend' via env FRONTEND_ADDR" "grpc"
        k8s_microservices_demo_recommendationservice_3360be -> k8s_microservices_demo_productcatalogservice_bd42bb "K8s Deployment 'recommendationservice' references 'productcatalogservice' via env PRODUCT_CATALOG_SERVICE_ADDR" "grpc"
        k8s_microservices_demo_recommendationservice_3360be -> k8s_microservices_demo_productcatalogservice_bd42bb "gRPC call from 'recommendationservice' to 'ProductCatalogService'" "grpc"
    }

    views {
        systemLandscape "landscape" {
            include *
            autoLayout tb
        }
        container microservices_demo "containers" {
            include *
            autoLayout lr
        }
        styles {
            element "External" {
                shape RoundedBox
                background #999999
                color #ffffff
            }
            element "Element" {
                shape RoundedBox
            }
            relationship "CrossRepo" {
                color #ff0000
                style dashed
            }
        }
    }
}
