workspace "Architecture — mybatis-3" "Auto-generated by nfr-review v<version> {
    !identifiers hierarchical

    model {
        mybatis_3 = softwareSystem "mybatis-3" "Primary system under analysis" {
            comp_mybatis_3_1e0051 = component "mybatis-3" "Root project component" "Java"
        }
        infra_github_com_3aeb00 = softwareSystem "Github Com" "Infrastructure: Github Com" {
            tags "External"
        }
        infra_mysql_430005 = softwareSystem "Mysql" "Infrastructure: Mysql" {
            tags "External"
        }
        infra_postgresql_a478b4 = softwareSystem "Postgresql" "Infrastructure: Postgresql" {
            tags "External"
        }
        infra_sqlserver_4270ce = softwareSystem "Sqlserver" "Infrastructure: Sqlserver" {
            tags "External"
        }
        infra_oracle_9202af = softwareSystem "Oracle" "Infrastructure: Oracle" {
            tags "External"
        }
        infra_h2_database_0ac217 = softwareSystem "H2 Database" "Infrastructure: H2 Database" {
            tags "External" "dev"
        }
        comp_mybatis_3_1e0051 -> infra_github_com_3aeb00 "HTTP endpoint at 'github.com'" "http"
        comp_mybatis_3_1e0051 -> infra_h2_database_0ac217 "Maven dependency implies mybatis-3 connects to h2-database" "jdbc:h2"
        comp_mybatis_3_1e0051 -> infra_mysql_430005 "Maven dependency implies mybatis-3 connects to mysql" "jdbc:mysql"
        comp_mybatis_3_1e0051 -> infra_oracle_9202af "Maven dependency implies mybatis-3 connects to oracle" "jdbc:oracle"
        comp_mybatis_3_1e0051 -> infra_postgresql_a478b4 "Maven dependency implies mybatis-3 connects to postgresql" "jdbc:postgresql"
        comp_mybatis_3_1e0051 -> infra_sqlserver_4270ce "Maven dependency implies mybatis-3 connects to sqlserver" "jdbc:sqlserver"
    }

    views {
        systemLandscape "landscape" {
            include *
            autoLayout tb
        }
        container mybatis_3 "containers" {
            include *
            autoLayout lr
        }
        styles {
            element "External" {
                shape RoundedBox
                background #999999
                color #ffffff
            }
            element "Element" {
                shape RoundedBox
            }
            relationship "CrossRepo" {
                color #ff0000
                style dashed
            }
        }
    }
}
