workspace "Architecture — prometheus-client-golang" "Auto-generated by nfr-review v<version> {
    !identifiers hierarchical

    model {
        prometheus_client_golang = softwareSystem "prometheus-client-golang" "Primary system under analysis" {
            nested_prometheus_client_golang_exp_db7272 = component "exp" "Nested project component" "Go"
        }
    }

    views {
        systemLandscape "landscape" {
            include *
            autoLayout tb
        }
        container prometheus_client_golang "containers" {
            include *
            autoLayout lr
        }
        styles {
            element "External" {
                shape RoundedBox
                background #999999
                color #ffffff
            }
            element "Element" {
                shape RoundedBox
            }
            relationship "CrossRepo" {
                color #ff0000
                style dashed
            }
        }
    }
}
