workspace "Architecture — rich" "Auto-generated by nfr-review v<version> {
    !identifiers hierarchical

    model {
        rich = softwareSystem "rich" "Primary system under analysis" {
            comp_rich_7baa68 = component "rich" "Root project component" "Python"
        }
    }

    views {
        systemLandscape "landscape" {
            include *
            autoLayout tb
        }
        container rich "containers" {
            include *
            autoLayout lr
        }
        styles {
            element "External" {
                shape RoundedBox
                background #999999
                color #ffffff
            }
            element "Element" {
                shape RoundedBox
            }
            relationship "CrossRepo" {
                color #ff0000
                style dashed
            }
        }
    }
}
