workspace "Architecture — sfml" "Auto-generated by nfr-review v<version> {
    !identifiers hierarchical

    model {
        sfml = softwareSystem "sfml" "Primary system under analysis" {
            nested_sfml_examples_1a0a94 = component "examples" "Nested project component" "C++"
        }
    }

    views {
        systemLandscape "landscape" {
            include *
            autoLayout tb
        }
        container sfml "containers" {
            include *
            autoLayout lr
        }
        styles {
            element "External" {
                shape RoundedBox
                background #999999
                color #ffffff
            }
            element "Element" {
                shape RoundedBox
            }
            relationship "CrossRepo" {
                color #ff0000
                style dashed
            }
        }
    }
}
