workspace "Architecture — spdlog" "Auto-generated by nfr-review v<version> {
    !identifiers hierarchical

    model {
        spdlog = softwareSystem "spdlog" "Primary system under analysis" {
            nested_spdlog_bench_162a9d = component "bench" "Nested project component" "C++"
            nested_spdlog_example_53acd4 = component "example" "Nested project component" "C++"
        }
        nested_spdlog_bench_162a9d -> nested_spdlog_example_53acd4 "add_subdirectory dependency on example via CMakeLists.txt" "cmake-add-subdirectory"
    }

    views {
        systemLandscape "landscape" {
            include *
            autoLayout tb
        }
        container spdlog "containers" {
            include *
            autoLayout lr
        }
        styles {
            element "External" {
                shape RoundedBox
                background #999999
                color #ffffff
            }
            element "Element" {
                shape RoundedBox
            }
            relationship "CrossRepo" {
                color #ff0000
                style dashed
            }
        }
    }
}
