workspace "Architecture — spring-petclinic" "Auto-generated by nfr-review v<version> {
    !identifiers hierarchical

    model {
        spring_petclinic = softwareSystem "spring-petclinic" "Primary system under analysis" {
            compose_spring_petclinic_mysql_5a694a = component "mysql" "Docker Compose service" "mysql"
            compose_spring_petclinic_postgres_b15904 = component "postgres" "Docker Compose service" "postgres"
            comp_spring_petclinic_998494 = component "spring-petclinic" "Root project component" "Java, Spring Boot"
        }
        infra_postgresql_a478b4 = softwareSystem "Postgresql" "Infrastructure: Postgresql" {
            tags "External"
        }
        infra_mysql_430005 = softwareSystem "Mysql" "Infrastructure: Mysql" {
            tags "External"
        }
        infra_h2_database_0ac217 = softwareSystem "H2 Database" "Infrastructure: H2 Database" {
            tags "External" "dev"
        }
        infra_database_3549b0 = softwareSystem "Database" "Infrastructure: Database" {
            tags "External"
        }
        infra_cache_5e1ece = softwareSystem "Cache" "Infrastructure: Cache" {
            tags "External"
        }
        comp_spring_petclinic_998494 -> compose_spring_petclinic_mysql_5a694a "JDBC connection to mysql at 'mysql'" "jdbc:mysql"
        comp_spring_petclinic_998494 -> infra_cache_5e1ece "Maven dependency implies spring-petclinic connects to cache" "cache"
        comp_spring_petclinic_998494 -> infra_database_3549b0 "Maven dependency implies spring-petclinic connects to database" "jpa"
        comp_spring_petclinic_998494 -> infra_h2_database_0ac217 "Maven dependency implies spring-petclinic connects to h2-database" "jdbc:h2"
        comp_spring_petclinic_998494 -> infra_mysql_430005 "Maven dependency implies spring-petclinic connects to mysql" "jdbc:mysql"
        comp_spring_petclinic_998494 -> infra_postgresql_a478b4 "JDBC connection to postgresql at 'postgresql'" "jdbc:postgresql"
    }

    views {
        systemLandscape "landscape" {
            include *
            autoLayout tb
        }
        container spring_petclinic "containers" {
            include *
            autoLayout lr
        }
        styles {
            element "External" {
                shape RoundedBox
                background #999999
                color #ffffff
            }
            element "Element" {
                shape RoundedBox
            }
            relationship "CrossRepo" {
                color #ff0000
                style dashed
            }
        }
    }
}
